# Generated by Django 4.2 on 2024-01-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
