# Generated by Django 4.2 on 2024-01-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_categoty_contact_status_contact_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
